### ISSUE TITLE
Keycloak support

### ISSUE THREAD

**Issue by JRPonte** [davidjrh/dnn.azureadprovider#93]
Hi,
Is it possible to use this module with keycloak (https://www.keycloak.org)? 
Thank you

**Comment by davidjrh** [comment]
Not with this module. Perhaps, with the Azure AD B2C module available at https://github.com/intelequia/dnn.azureadb2cprovider, you could setup an OpenID Connect (see https://learn.microsoft.com/en-us/azure/active-directory-b2c/openid-connect), but would be redundant, since both KeyCloack and Azure AD B2C have the same purpose. 

To me, the correct solution would be to implement a new auth provider module like this one, perhaps by using a for of this module.
